CREATE DATABASE [EncounterCreatorS2G3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EncounterCreator', FILENAME = N'D:\Database\MSSQL15.MSSQLSERVER\MSSQL\DATA\EncounterCreator.mdf' , SIZE = 10240KB , MAXSIZE = 102400KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'EncounterCreator_log', FILENAME = N'D:\Database\MSSQL15.MSSQLSERVER\MSSQL\DATA\EncounterCreator_log.ldf' , SIZE = 2048KB , MAXSIZE = 51200KB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EncounterCreatorS2G3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EncounterCreatorS2G3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET ARITHABORT OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET  MULTI_USER 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EncounterCreatorS2G3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EncounterCreatorS2G3] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EncounterCreatorS2G3] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EncounterCreatorS2G3] SET  READ_WRITE 
GO

